---
title: "Alineamiento de secuencias II"
subtitle: "Licenciatura en Ciencias Genómicas, Transcriptómica, Semestre 2025-2"
description: "Clase 4 – Análisis bioinformático: alineamiento de secuencias con genomas no anotados"
author:
- Bernardo Chombo Álvarez
- David Valle García
date: last-modified
format:
  html:
    self-contained: true
    toc: true
    toc-expand: true
    toc-depth: 4
    theme: flatly
    highlight-style: monokai
    code-fold: false
    code-overflow: scroll
    code-block-border-left: "#31BAE9"
    code-block-bg: "#011627"
    page-layout: article
    fig-align: center
    df-print: paged
    code-line-numbers: true
    code-copy: false
    css: ../css/styles.css
execute: 
  eval: true
  echo: true
  warning: false
  include: true
  error: false
  message: false
fontsize: 11pt
editor: visual
mainfont: Calibri
sansfont: Calibri
monofont: Calibri
knitr:
  opts_chunk:
    comment: "##"
  opts_knit:
    kable: true
---

## 1. Alineamiento con genomas no anotados

En la clase pasada se vieron los alineamientos con genomas anotados, en esta se verá cómo alinear datos de secuenciación de *RNA-seq* con genomas no anotados.

Por lo general se usan estos alineadores cuando NO se considera splicing y se está trabajando con datos de *ChIP-seq* o *microRNA-seq*

### 1.1 Diferencias entre *Bowtie* y *Bowtie2*

Existen pocas pero putnuales referencias entyre alineadores para genomas no anotados y se espera que se usen de acuerdo a lo más conveniente.

#### 1.1.1 Compatibilidad con lecturas cortas y largas

-   **Bowtie**: Diseñado para alinear lecturas cortas (25-50bp).
-   **Bowtie2**: Diseñado para alinear lecturas cortas y largas (\> 50 bp).

#### 1.1.2 Alineación de lecturas emparejadas

-   **Bowtie**: Limitado para manejar *paired-end reads*.
-   **Bowtie2**: Permite manejar *paired-end reads*.

#### 1.1.3 Capacidad de permitir desajustes e indels

-   **Bowtie**: No maneja bien los indels.
-   **Bowtie2**: Maneja bien los indels, lo que lo hace mejor para lecturas más largas y variantes estructurales.

#### 1.1.4 Rendimiento

-   **Bowtie**: Muy rápido para *short-reads* con pocas variaciones, pero menos preciso para escenarios más complejos.
-   **Bowtie2**: Más lento que *Bowtie* para lecturas cortas, pero más versátil y eficiente para lecturas largas.

#### 1.1.5 Sensibilidad

-   **Bowtie**: *Trade-off* rápidez vs. sensibilidad.
-   **Bowtie2**: Menos sensible debido a la capacidad de manejar alineaciones locales y globales.

#### 1.1.6 Modos de alineación

-   **Bowtie**: Sólo permite alineamiento global.
-   **Bowtie2**: Alineamiento local y global.

#### 1.1.7 Consumo de recursos

-   **Bowtie**: Más ligero en términos de memoria, eficiente para genomas pequeños.
-   **Bowtie2**: Requiere más memoria que *Bowtie*.

#### 1.1.8 Tecnologías de secuenciación

-   **Bowtie**: Principalmente diseñado para lecturas de Illumina.
-   **Bowtie2**: Compatible con NGS modernas como PacBio y Oxford Nanopore.

En general comparten casi los mismos parámetros, excluyendo aquellos que involucran las diferencias de alineamiento (global, local).

[Manual de bowtie](https://bowtie-bio.sourceforge.net/manual.shtml)

### 1.2 Bowtie2

Ideal para lecturas de al menos 50 bp (\< 50 deben de usar bowtie1). EL default es un alineamiento *end-to-end* y funciona mejor cuando el ya se cortaron por cuestiones

de calidad y para remover secuencias de adaptadores. De no haber limpiado previamente los *reads* se recomienda hacer ***soft-clipping*** el cual ignora las porciones a los exremos de las *reads* y le asigna una penalización menor a las bases no alineadas.

[Manual bowtie2](https://bowtie-bio.sourceforge.net/bowtie2/manual.shtml)

#### 1.2.1 Construcción de un index

```{bash}
#| eval: false
bowtie2-build <path_to_reference_genome.fa> <prefix_to_name_indexes>
```

#### 1.2.2 Alineamiento

Argumentos importantes para el alineamiento con **Bowtie2**:

-   `-p`: number of cores
-   `-q`: reads are in FASTQ format
-   `--local`: local alignment feature to perform soft-clipping
-   `-x`: /path/to/genome_indices_directory
-   `-U`: /path/to/FASTQ_file
-   `-S`: /path/to/output/SAM_file
-   `-N`: number of mismatches allowed in a seed
-   `-L`: length of the seed substrings to align
-   `-k`: searches for the *k* best valid alignments
-   `-m`: maixmum number of alignments
-   `--best`: best alignments only
-   `--strata`: alignments in the best stratum only

```{bash}
#| eval: false
## Create bowtie2 directory results
mkdir ~/transcriptomica/results/bowtie2

## Run bowtie2
bowtie2 -p 10 -q -N 0 -L 18 -m 10 --best --strata \
-x ~/path/to/bowtie_indexes/mm10 \
-U ~/path/to/FASTQ_file.fastq.gz \
-S ~/path/to/output/SAM_file.sam

```

<br>

## Referencias

-   <https://hbctraining.github.io/Intro-to-ChIPseq-flipped/lessons/04_alignment_using_bowtie2.html>
